# task: pose generation
name: grasp_gen
lr: 1e-4
eval_interval: 1
eval_visualize: 1

train:
  batch_size: 64
#  num_workers: 4
  num_workers: 0
  num_epochs: 1000
  log_step: 100

test:
  batch_size: 2
  num_workers: 0

dataset:
  name: MultiDexShadowHandUR
  desc: '[MultiDex ShadowHand] -- dataset used for grasp pose generation condition on 3D object'
  modeling_keys: ['allDoFs']
  num_points: 2048
  frame_interval_train: 5
  frame_interval_test: 10
  device: cuda
  use_color: false
  use_normal: false
  is_downsample: true
  data_dir: ${paths.multidex_shadowhand_dir}
  data_dir_slurm: ${task.dataset.data_dir}
  scene_path: ${paths.multidex_object_pcds_path}
  scene_path_slurm: ${task.dataset.scene_path}

  train_transforms: ['NumpyToTensor']
  test_transforms: ['NumpyToTensor']
  transform_cfg: {}

visualizer:
  name: GraspGenVisualizer
  visualize: false
  ksample: 4
